// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGE5euWcxpXC5wrLXVtdmmkcDV1bseWNY',
    appId: '1:695534497324:web:6dfa668587f5e560e8eb89',
    messagingSenderId: '695534497324',
    projectId: 'projeto2-9e1ed',
    authDomain: 'projeto2-9e1ed.firebaseapp.com',
    databaseURL: 'https://projeto2-9e1ed-default-rtdb.firebaseio.com',
    storageBucket: 'projeto2-9e1ed.firebasestorage.app',
    measurementId: 'G-KSZJEZF3Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDlbVsttFamkCRGxfvjnt5tdYwS1510Qg',
    appId: '1:695534497324:android:fd4322d28ce793d1e8eb89',
    messagingSenderId: '695534497324',
    projectId: 'projeto2-9e1ed',
    databaseURL: 'https://projeto2-9e1ed-default-rtdb.firebaseio.com',
    storageBucket: 'projeto2-9e1ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDckdtNVqxhRGL8oZNpFk5kkg2iB3A40po',
    appId: '1:695534497324:ios:b1dec51f1da0b5b7e8eb89',
    messagingSenderId: '695534497324',
    projectId: 'projeto2-9e1ed',
    databaseURL: 'https://projeto2-9e1ed-default-rtdb.firebaseio.com',
    storageBucket: 'projeto2-9e1ed.firebasestorage.app',
    iosBundleId: 'com.example.projeto2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDckdtNVqxhRGL8oZNpFk5kkg2iB3A40po',
    appId: '1:695534497324:ios:b1dec51f1da0b5b7e8eb89',
    messagingSenderId: '695534497324',
    projectId: 'projeto2-9e1ed',
    databaseURL: 'https://projeto2-9e1ed-default-rtdb.firebaseio.com',
    storageBucket: 'projeto2-9e1ed.firebasestorage.app',
    iosBundleId: 'com.example.projeto2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGE5euWcxpXC5wrLXVtdmmkcDV1bseWNY',
    appId: '1:695534497324:web:4566fdc960a9aa25e8eb89',
    messagingSenderId: '695534497324',
    projectId: 'projeto2-9e1ed',
    authDomain: 'projeto2-9e1ed.firebaseapp.com',
    databaseURL: 'https://projeto2-9e1ed-default-rtdb.firebaseio.com',
    storageBucket: 'projeto2-9e1ed.firebasestorage.app',
    measurementId: 'G-8MLCE5C0H6',
  );
}
